Repository sofastack/sofa-bolt, pull requests merged in 2018-07, with the labels that each got.

#62 support multi-interest feature in MultiInterestUserProcessor
  src/main/java/com/alipay/remoting/RemotingServer.java
  src/main/java/com/alipay/remoting/rpc/RpcClient.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/main/java/com/alipay/remoting/rpc/protocol/AbstractMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/AsynMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/MultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/SyncMutiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/UserProcessorRegisterHelper.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/UserProcessorRegisterHelperTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/BasicUsage_MultiInterestUserProcessorTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/MultiInterestBaseRequestBody.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/RequestBodyC1.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/RequestBodyC2.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/SimpleClientMultiInterestUserProcessor.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/SimpleServerMultiInterestUserProcessor.java
Labels: dev:feature

#69 (feature) add pmd plugin fix #63
  .middleware-common/pmd_rule_set.xml
  pom.xml
  src/main/java/com/alipay/remoting/AbstractRemotingProcessor.java
  src/main/java/com/alipay/remoting/AbstractRemotingServer.java
  src/main/java/com/alipay/remoting/CommonCommandCode.java
  src/main/java/com/alipay/remoting/Connection.java
  src/main/java/com/alipay/remoting/ConnectionEventHandler.java
  src/main/java/com/alipay/remoting/DefaultConnectionManager.java
  src/main/java/com/alipay/remoting/NamedThreadFactory.java
  src/main/java/com/alipay/remoting/ProtocolCode.java
  src/main/java/com/alipay/remoting/RandomSelectStrategy.java
  src/main/java/com/alipay/remoting/ReconnectManager.java
  src/main/java/com/alipay/remoting/RemotingServer.java
  src/main/java/com/alipay/remoting/ServerIdleHandler.java
  src/main/java/com/alipay/remoting/SystemProperties.java
  src/main/java/com/alipay/remoting/Url.java
  src/main/java/com/alipay/remoting/connection/AbstractConnectionFactory.java
  src/main/java/com/alipay/remoting/connection/DefaultConnectionFactory.java
  src/main/java/com/alipay/remoting/rpc/DefaultInvokeFuture.java
  src/main/java/com/alipay/remoting/rpc/HeartbeatHandler.java
  src/main/java/com/alipay/remoting/rpc/RpcAddressParser.java
  src/main/java/com/alipay/remoting/rpc/RpcClient.java
  src/main/java/com/alipay/remoting/rpc/RpcCodec.java
  src/main/java/com/alipay/remoting/rpc/RpcCommand.java
  src/main/java/com/alipay/remoting/rpc/RpcConnectionFactory.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/main/java/com/alipay/remoting/rpc/RpcTaskScanner.java
  src/main/java/com/alipay/remoting/rpc/protocol/AsynMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcCommandCode.java
  src/main/java/com/alipay/remoting/rpc/protocol/SyncMutiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/UserProcessorRegisterHelper.java
  src/main/java/com/alipay/remoting/util/RunStateRecordedFutureTask.java
  src/main/java/com/alipay/remoting/util/Switch.java
  src/test/java/com/alipay/remoting/RemotingServerTest.java
  src/test/java/com/alipay/remoting/inner/connection/ConcurrentCreateConnectionTest.java
  src/test/java/com/alipay/remoting/inner/connection/RpcConnectionManagerTest.java
  src/test/java/com/alipay/remoting/rpc/exception/BadServerIpTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/UserProcessorRegisterHelperTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/BasicUsage_MultiInterestUserProcessorTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/SimpleClientMultiInterestUserProcessor.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/SimpleServerMultiInterestUserProcessor.java
Labels: dev:feature, dev:format

#71 Bugfix/pmd problems
  src/main/java/com/alipay/remoting/ProcessorManager.java
  src/main/java/com/alipay/remoting/RemotingContext.java
  src/test/java/com/alipay/remoting/ProcessorManagerTest.java
  src/test/java/com/alipay/remoting/rpc/common/SimpleClientUserProcessor.java
  src/test/java/com/alipay/remoting/rpc/common/SimpleServerUserProcessor.java
  src/test/java/com/alipay/remoting/rpc/timeout/ServerTimeoutSwitchTest.java
Labels: bug

#73 (tuning) fix #44
  src/main/java/com/alipay/remoting/AbstractRemotingServer.java
  src/main/java/com/alipay/remoting/RemotingServer.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
Labels: dev:tuning

#74 (tuning) fix #22
  src/main/java/com/alipay/remoting/CommandFactory.java
  src/main/java/com/alipay/remoting/rpc/RpcCommandFactory.java
  src/main/java/com/alipay/remoting/rpc/RpcResponseResolver.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcCommandHandler.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcRequestProcessor.java
Labels: dev:tuning
