Repository sofastack/sofa-bolt, pull requests merged in 2018-06, with the labels that each got.

#37 (tuning) change command factory visibility
  src/main/java/com/alipay/remoting/BaseRemoting.java
Labels: dev:tuning

#34 [feature] support native transport (epoll)
  src/main/java/com/alipay/remoting/Configs.java
  src/main/java/com/alipay/remoting/SystemProperties.java
  src/main/java/com/alipay/remoting/rpc/RpcConnectionFactory.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/main/java/com/alipay/remoting/util/NettyEventLoopUtil.java
Labels: dev:feature

#48 (tuning) tune some logic of epoll util, and modify some comments
  src/main/java/com/alipay/remoting/Configs.java
  src/main/java/com/alipay/remoting/SystemProperties.java
  src/main/java/com/alipay/remoting/rpc/RpcConnectionFactory.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/main/java/com/alipay/remoting/util/NettyEventLoopUtil.java
Labels: dev:tuning

#55 (tuning) fix build error of jdk16 using travis ci
  .middleware-common/.travis.settings.xml
  .travis.yml
Labels: dev:tuning

#59 (bugfix) re-add epoll feature for client
  src/main/java/com/alipay/remoting/connection/AbstractConnectionFactory.java
Labels: bug

#61 (tune) fix #53
  src/main/java/com/alipay/remoting/DefaultConnectionManager.java
  src/main/java/com/alipay/remoting/RandomSelectStrategy.java
Labels: dev:tuning
