Repository sofastack/sofa-bolt, pull requests merged in 2018-09, with the labels that each got.

#84 (feature) RPC 层支持从 IO 线程派发 mesage list
  src/main/java/com/alipay/remoting/config/ConfigManager.java
  src/main/java/com/alipay/remoting/rpc/RpcConfigManager.java
  src/main/java/com/alipay/remoting/rpc/RpcConfigs.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcCommandHandler.java
  src/test/java/com/alipay/remoting/rpc/RpcConfigManagerTest.java
Labels: dev:feature

#87 Fix the bug that RemotingServer can be closed repeatedly.
  src/main/java/com/alipay/remoting/AbstractRemotingServer.java
  src/main/java/com/alipay/remoting/RemotingServer.java
  src/test/java/com/alipay/remoting/rpc/connectionmanage/ScheduledDisconnectStrategyTest.java
  src/test/java/com/alipay/remoting/rpc/watermark/WaterMarkInitTest.java
Labels: bug

#88 fix some coding specification issues
  src/main/java/com/alipay/remoting/CommandDecoder.java
  src/main/java/com/alipay/remoting/CommandEncoder.java
  src/main/java/com/alipay/remoting/CommandHandler.java
  src/main/java/com/alipay/remoting/ConnectionHeartbeatManager.java
  src/main/java/com/alipay/remoting/ConnectionSelectStrategy.java
  src/main/java/com/alipay/remoting/CustomSerializer.java
  src/main/java/com/alipay/remoting/InvokeCallback.java
  src/main/java/com/alipay/remoting/InvokeCallbackListener.java
  src/main/java/com/alipay/remoting/InvokeFuture.java
  src/main/java/com/alipay/remoting/RemotingAddressParser.java
  src/main/java/com/alipay/remoting/Scannable.java
  src/main/java/com/alipay/remoting/codec/AbstractBatchDecoder.java
  src/main/java/com/alipay/remoting/codec/Codec.java
  src/main/java/com/alipay/remoting/codec/ProtocolCodeBasedDecoder.java
  src/main/java/com/alipay/remoting/config/switches/ProtocolSwitch.java
  src/main/java/com/alipay/remoting/exception/CodecException.java
  src/main/java/com/alipay/remoting/rpc/DefaultInvokeFuture.java
  src/main/java/com/alipay/remoting/rpc/RpcClientRemoting.java
  src/main/java/com/alipay/remoting/rpc/RpcConfigManager.java
  src/main/java/com/alipay/remoting/rpc/RpcResponseFuture.java
  src/main/java/com/alipay/remoting/rpc/RpcResponseResolver.java
  src/main/java/com/alipay/remoting/rpc/exception/InvokeTimeoutException.java
  src/main/java/com/alipay/remoting/rpc/protocol/AbstractMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/AbstractUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/AsynMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/MultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcAsyncContext.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcCommandDecoder.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcCommandDecoderV2.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcDeserializeLevel.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcHeartbeatTrigger.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcProtocol.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcProtocolDecoder.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcProtocolManager.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcRequestCommand.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcRequestProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcResponseCommand.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcResponseProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/SyncMutiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/UserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/UserProcessorRegisterHelper.java
  src/main/java/com/alipay/remoting/serialization/Serializer.java
  src/test/java/com/alipay/remoting/rpc/connectionmanage/ScheduledDisconnectStrategyTest.java
Labels: dev:format
