Repository sofastack/sofa-bolt, pull requests merged in 2018-05, with the labels that each got.

#21 (tuning) refactor start logic of remoting server
  pom.xml
  src/main/java/com/alipay/remoting/RemotingServer.java
  src/test/java/com/alipay/remoting/RemotingServerTest.java
Labels: dev:tuning

#25 (tuning) log conf modify
  LICENSE
  src/main/java/com/alipay/remoting/log/BoltLoggerFactory.java
  src/main/resources/com/alipay/remoting/log/log4j/log-conf.xml
  src/main/resources/com/alipay/remoting/log/log4j2/log-conf.xml
  src/main/resources/com/alipay/remoting/log/logback/log-conf.xml
Labels: dev:tuning

#28 fix maven-javadoc-plugin build ERROR with JDK 1.8
  pom.xml
Labels: dev:compatibility

#31 fix threadpools shutdown problems (issues 14)
  pom.xml
  src/main/java/com/alipay/remoting/ConnectionEventHandler.java
  src/main/java/com/alipay/remoting/DefaultConnectionManager.java
  src/main/java/com/alipay/remoting/DefaultConnectionMonitor.java
  src/main/java/com/alipay/remoting/ProcessorManager.java
  src/main/java/com/alipay/remoting/TimerHolder.java
  src/main/java/com/alipay/remoting/rpc/RpcConnectionFactory.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
Labels: bug

#36 Tuning/threadpool exit
  src/main/java/com/alipay/remoting/RemotingServer.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/test/java/com/alipay/remoting/demo/RpcClientDemoByMain.java
  src/test/java/com/alipay/remoting/demo/RpcServerDemoByMain.java
  src/test/java/com/alipay/remoting/rpc/RpcServerTest.java
  src/test/java/com/alipay/remoting/util/ThreadTestUtils.java
Labels: dev:tuning
