Repository sofastack/sofa-bolt, pull requests merged in 2019-12, with the labels that each got.

#194 fix spelling mistake and some test codes
  src/main/java/com/alipay/remoting/ProtocolCode.java
  src/main/java/com/alipay/remoting/Url.java
  src/main/java/com/alipay/remoting/rpc/RpcInvokeCallbackListener.java
  src/main/java/com/alipay/remoting/rpc/RpcResponseResolver.java
  src/main/java/com/alipay/remoting/rpc/protocol/AsyncMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/AsyncUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/SyncMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/SyncUserProcessor.java
  src/test/java/com/alipay/remoting/rpc/common/PortScan.java
  src/test/java/com/alipay/remoting/rpc/exception/ExceptionTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/UserProcessorRegisterHelperTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/SimpleClientMultiInterestUserProcessor.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/SimpleServerMultiInterestUserProcessor.java
Labels: bug, cla:yes, size/L

#199 support server random port constructor. fix #196
  src/main/java/com/alipay/remoting/AbstractLifeCycle.java
  src/main/java/com/alipay/remoting/AbstractRemotingServer.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/test/java/com/alipay/remoting/rpc/RpcServerTest.java
Labels: bug, cla:yes, size/M

#205 complete tcp related config. see #171
  src/main/java/com/alipay/remoting/config/BoltGenericOption.java
  src/main/java/com/alipay/remoting/config/ConfigManager.java
  src/main/java/com/alipay/remoting/config/Configs.java
  src/main/java/com/alipay/remoting/connection/AbstractConnectionFactory.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/test/java/com/alipay/remoting/inner/utiltest/ConfigManagerTest.java
Labels: cla:yes, size/M

#201 Optimization/connection manager constructor fix #153
  src/main/java/com/alipay/remoting/DefaultConnectionManager.java
Labels: bug, cla:yes, size/XS

#204 support availability check with life cycle. #195
  src/main/java/com/alipay/remoting/AbstractLifeCycle.java
  src/main/java/com/alipay/remoting/ReconnectManager.java
  src/main/java/com/alipay/remoting/RemotingAddressParser.java
  src/main/java/com/alipay/remoting/rpc/RpcAddressParser.java
  src/main/java/com/alipay/remoting/rpc/RpcClient.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/test/java/com/alipay/remoting/rpc/LifeCycleTest.java
Labels: cla:yes, size/L

#207 Fix/multi processor bug
  src/main/java/com/alipay/remoting/ProtocolCode.java
  src/main/java/com/alipay/remoting/Url.java
  src/main/java/com/alipay/remoting/rpc/RpcInvokeCallbackListener.java
  src/main/java/com/alipay/remoting/rpc/RpcResponseResolver.java
  src/main/java/com/alipay/remoting/rpc/protocol/AsyncMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/AsyncUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcRequestProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/SyncMultiInterestUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/SyncUserProcessor.java
  src/test/java/com/alipay/remoting/rpc/common/PortScan.java
  src/test/java/com/alipay/remoting/rpc/exception/ExceptionTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/UserProcessorRegisterHelperTest.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/SimpleClientMultiInterestUserProcessor.java
  src/test/java/com/alipay/remoting/rpc/userprocessor/multiinterestprocessor/SimpleServerMultiInterestUserProcessor.java
Labels: bug, cla:yes, size/L

#200 support user processor with life cycle interface fix #123
  src/main/java/com/alipay/remoting/rpc/RpcClient.java
  src/main/java/com/alipay/remoting/rpc/RpcServer.java
  src/main/java/com/alipay/remoting/rpc/protocol/AbstractUserProcessor.java
  src/main/java/com/alipay/remoting/rpc/protocol/UserProcessor.java
Labels: bug, cla:yes, size/M

#208 fix some codes
  src/main/java/com/alipay/remoting/connection/AbstractConnectionFactory.java
Labels: bug, cla:yes, size/XS

#211 fix spelling mistakes
  src/main/java/com/alipay/remoting/NamedThreadFactory.java
Labels: First-time contributor, bug, cla:no, size/XS
