Repository sofastack/sofa-bolt, pull requests merged in 2019-11, with the labels that each got.

#189 upgrade netty version to fix CNNVD-201909-1264 vulnerability
  pom.xml
Labels: bug, size/XS

#191 One should be serialized and one is deserialized
  src/test/java/com/alipay/remoting/rpc/serializer/NormalStringCustomSerializer.java
Labels: First-time contributor, cla:no, size/XS

#188 fix AbstractLifeCycle concurrency problem Fixes gh-163
  src/main/java/com/alipay/remoting/AbstractLifeCycle.java
Labels: First-time contributor, bug, cla:yes, size/S
