Repository sofastack/sofa-bolt, pull requests merged in 2021-01, with the labels that each got.

#250 set thread name
  src/main/java/com/alipay/remoting/ReconnectManager.java
Labels: cla:yes, size/XS

#249 1.6.3-snapshot
  pom.xml
Labels: First-time contributor, cla:yes, size/XS

#248 optimized log4j2 config
  src/main/resources/com/alipay/remoting/log/log4j2/log-conf.xml
Labels: First-time contributor, cla:yes, size/S
