Repository sofastack/sofa-bolt, pull requests merged in 2022-03, with the labels that each got.

#281 fix int cast to short
  src/main/java/com/alipay/remoting/rpc/RpcCommand.java
  src/test/java/com/alipay/remoting/rpc/RpcCommandTest.java
Labels: bug, cla:yes, size/M

#282 support ipv6 address parse
  src/main/java/com/alipay/remoting/rpc/RpcAddressParser.java
  src/test/java/com/alipay/remoting/RpcWithIpv6Test.java
  src/test/java/com/alipay/remoting/rpc/RpcAddressParserTest.java
  src/test/java/com/alipay/remoting/rpc/RpcCommandTest.java
  src/test/java/com/alipay/remoting/simpledemo/QuickStartServerAndClientWithIpv6.java
Labels: cla:yes, size/L

#284 Update qrcode in README.md
  README.md
Labels: cla:yes, size/XS
