Repository sofastack/sofa-bolt, pull requests merged in 2024-04, with the labels that each got.

#334 Fix: sendResponse if RpcRequestProcessor.doProcess throw Throwable
  src/main/java/com/alipay/remoting/rpc/protocol/RpcRequestProcessor.java
  src/test/java/com/alipay/remoting/rpc/exception/ExceptionTest.java
Labels: bug, cla:yes, First-time contributor, size/M

#346 improve: write and flush methods are provided
  src/main/java/com/alipay/remoting/RemotingContext.java
Labels: cla:yes, size/S

#335 Fix: serialize exception response
  src/main/java/com/alipay/remoting/rpc/protocol/RpcRequestProcessor.java
  src/test/java/com/alipay/remoting/rpc/serializer/ClassCustomSerializerTest.java
Labels: bug, cla:yes, First-time contributor, size/M

#347 fix remoteContext concurrency problem when msg batch handler
  src/main/java/com/alipay/remoting/RemotingContext.java
  src/main/java/com/alipay/remoting/rpc/protocol/RpcCommandHandler.java
  src/test/java/com/alipay/remoting/rpc/protocol/RpcCommandHandlerTest.java
Labels: bug, cla:yes, question, size/L

#348 upgrade bolt version to 1.6.8
  pom.xml
Labels: cla:yes, size/XS
